### PR TITLE
feat(acir): log all witnesses in opcodes (easier debugging)

### PR DESCRIPTION
**Pull request by joss-aztec**
# Related issue(s)

(If it does not already exist, first create a GitHub issue that describes the problem this Pull Request (PR) solves before creating the PR and link it here.)

Resolves (link to issue)

# Description

## Summary of changes

(Describe the changes in this PR. Point out breaking changes if any.)

## Dependency additions / changes

(If applicable.)

## Test additions / changes

(If applicable.)

# Checklist

- [ ] I have tested the changes locally.
- [ ] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` with default settings.
- [ ] I have [linked](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) this PR to the issue(s) that it resolves.
- [ ] I have reviewed the changes on GitHub, line by line.
- [ ] I have ensured all changes are covered in the description.

# Additional context

(If applicable.)

### CODE REVIEW

**Review by vezenovm — APPROVED** [review]

**Comment by TomAFrench** [comment]
Going to add this to the 0.12.0 milestone as it looks fairly uncontroversial.

**Comment by vezenovm** [comment]
> Going to add this to the 0.12.0 milestone as it looks fairly uncontroversial.

We did it for debugging brillig as we had smaller examples we wanted to work through where we could see every witness. I'm ok with adding it in `0.12.0` but we should consider if there is a way we could truncate the debug output for larger circuits.

**Comment by TomAFrench** [comment]
Ah, I didn't see this was into the hacky branch.

**Comment by kevaundray** [comment]
I think this can be closed and an issue opened up if we still want this functionality in the master branch

**Pull request closed without merging**
