### PR TITLE
chore: Release 0.27.0

### PR DESCRIPTION
**Pull request by kevaundray**
:robot: I have created a release *beep* *boop*
---

<details><summary>barretenberg_blackbox_solver: 0.27.0</summary>

### ⚠ BREAKING CHANGES

* Separate barretenberg solver from generic blackbox solver code ([#554](https://github.com/noir-lang/acvm/issues/554))

### Bug Fixes

* Empty commit to trigger release-please ([e8f0748](https://github.com/noir-lang/acvm/commit/e8f0748042ef505d59ab63266d3c36c5358ee30d))

### Miscellaneous Chores

* Separate barretenberg solver from generic blackbox solver code ([#554](https://github.com/noir-lang/acvm/issues/554)) ([a4b9772](https://github.com/noir-lang/acvm/commit/a4b97722a0892fe379ff075e6080675adafdce0e))
</details>

<details><summary>root: 0.27.0</summary>

### ⚠ BREAKING CHANGES

* Separate barretenberg solver from generic blackbox solver code ([#554](https://github.com/noir-lang/acvm/issues/554))

### Features

* **acir:** add method on `Circuit` to return assert message ([#551](https://github.com/noir-lang/acvm/issues/551)) ([ee18cde](https://github.com/noir-lang/acvm/commit/ee18cde3537b2be6714061af0bc9ef3793929f7f))

### Bug Fixes

* bump brillig_vm version in release please ([#556](https://github.com/noir-lang/acvm/issues/556)) ([f6c7823](https://github.com/noir-lang/acvm/commit/f6c7823b3be2b85a6ce8dc4af7a3b57ee7a577db))
* use the exact version for the hex crate ([#546](https://github.com/noir-lang/acvm/issues/546)) ([2a546e5](https://github.com/noir-lang/acvm/commit/2a546e5b5cc9f39737ad81f8e96d58313a74eced))

### Miscellaneous Chores

* Separate barretenberg solver from generic blackbox solver code ([#554](https://github.com/noir-lang/acvm/issues/554)) ([a4b9772](https://github.com/noir-lang/acvm/commit/a4b97722a0892fe379ff075e6080675adafdce0e))
</details>

<details><summary>acir: 0.27.0</summary>

### Features

* **acir:** add method on `Circuit` to return assert message ([#551](https://github.com/noir-lang/acvm/issues/551)) ([ee18cde](https://github.com/noir-lang/acvm/commit/ee18cde3537b2be6714061af0bc9ef3793929f7f))
</details>

<details><summary>acir_field: 0.27.0</summary>

### ⚠ BREAKING CHANGES

* Separate barretenberg solver from generic blackbox solver code ([#554](https://github.com/noir-lang/acvm/issues/554))

### Miscellaneous Chores

* Separate barretenberg solver from generic blackbox solver code ([#554](https://github.com/noir-lang/acvm/issues/554)) ([a4b9772](https://github.com/noir-lang/acvm/commit/a4b97722a0892fe379ff075e6080675adafdce0e))
</details>

<details><summary>acvm: 0.27.0</summary>

### ⚠ BREAKING CHANGES

* Separate barretenberg solver from generic blackbox solver code ([#554](https://github.com/noir-lang/acvm/issues/554))

### Miscellaneous Chores

* Separate barretenberg solver from generic blackbox solver code ([#554](https://github.com/noir-lang/acvm/issues/554)) ([a4b9772](https://github.com/noir-lang/acvm/commit/a4b97722a0892fe379ff075e6080675adafdce0e))
</details>

<details><summary>acvm_blackbox_solver: 0.27.0</summary>

### ⚠ BREAKING CHANGES

* Separate barretenberg solver from generic blackbox solver code ([#554](https://github.com/noir-lang/acvm/issues/554))

### Bug Fixes

* use the exact version for the hex crate ([#546](https://github.com/noir-lang/acvm/issues/546)) ([2a546e5](https://github.com/noir-lang/acvm/commit/2a546e5b5cc9f39737ad81f8e96d58313a74eced))

### Miscellaneous Chores

* Separate barretenberg solver from generic blackbox solver code ([#554](https://github.com/noir-lang/acvm/issues/554)) ([a4b9772](https://github.com/noir-lang/acvm/commit/a4b97722a0892fe379ff075e6080675adafdce0e))
</details>

<details><summary>acvm_js: 0.27.0</summary>

### ⚠ BREAKING CHANGES

* Separate barretenberg solver from generic blackbox solver code ([#554](https://github.com/noir-lang/acvm/issues/554))

### Miscellaneous Chores

* Separate barretenberg solver from generic blackbox solver code ([#554](https://github.com/noir-lang/acvm/issues/554)) ([a4b9772](https://github.com/noir-lang/acvm/commit/a4b97722a0892fe379ff075e6080675adafdce0e))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * acvm bumped from 0.26.1 to 0.27.0
    * barretenberg_blackbox_solver bumped from 0.26.1 to 0.27.0
</details>

<details><summary>acvm_stdlib: 0.27.0</summary>

### Miscellaneous Chores

* **acvm_stdlib:** Synchronize acvm versions
</details>

<details><summary>brillig: 0.27.0</summary>

### Miscellaneous Chores

* **brillig:** Synchronize acvm versions
</details>

<details><summary>brillig_vm: 0.27.0</summary>

### ⚠ BREAKING CHANGES

* Separate barretenberg solver from generic blackbox solver code ([#554](https://github.com/noir-lang/acvm/issues/554))

### Miscellaneous Chores

* Separate barretenberg solver from generic blackbox solver code ([#554](https://github.com/noir-lang/acvm/issues/554)) ([a4b9772](https://github.com/noir-lang/acvm/commit/a4b97722a0892fe379ff075e6080675adafdce0e))
</details>

---
This PR was generated with [Release Please](https://github.com/googleapis/release-please). See [documentation](https://github.com/googleapis/release-please#release-please).

### CODE REVIEW

**Review by TomAFrench — APPROVED** [review]

**Comment by kevaundray** [comment]
:robot: Release is at https://github.com/noir-lang/acvm/releases/tag/root-v0.27.0 :sunflower:

**Comment by kevaundray** [comment]
:robot: Release is at https://github.com/noir-lang/acvm/releases/tag/acir-v0.27.0 :sunflower:

**Comment by kevaundray** [comment]
:robot: Release is at https://github.com/noir-lang/acvm/releases/tag/acir_field-v0.27.0 :sunflower:

**Comment by kevaundray** [comment]
:robot: Release is at https://github.com/noir-lang/acvm/releases/tag/acvm-v0.27.0 :sunflower:

**Comment by kevaundray** [comment]
:robot: Release is at https://github.com/noir-lang/acvm/releases/tag/acvm_js-v0.27.0 :sunflower:

**Comment by kevaundray** [comment]
:robot: Release is at https://github.com/noir-lang/acvm/releases/tag/brillig-v0.27.0 :sunflower:

**Comment by kevaundray** [comment]
:robot: Release is at https://github.com/noir-lang/acvm/releases/tag/brillig_vm-v0.27.0 :sunflower:

**Comment by kevaundray** [comment]
:robot: Release is at https://github.com/noir-lang/acvm/releases/tag/acvm_stdlib-v0.27.0 :sunflower:

**Comment by kevaundray** [comment]
:robot: Release is at https://github.com/noir-lang/acvm/releases/tag/acvm_blackbox_solver-v0.27.0 :sunflower:

**Comment by kevaundray** [comment]
:robot: Release is at https://github.com/noir-lang/acvm/releases/tag/barretenberg_blackbox_solver-v0.27.0 :sunflower:

**Pull request merged**
