### PR TITLE
feat(brillig): Allow returning with an empty call stack

### PR DESCRIPTION
**Pull request by ludamad**
See https://github.com/noir-lang/acvm/issues/379

### CODE REVIEW

**Comment by ludamad** [comment]
Actually questioning this now. We still need entry point wrappers around functions if we start to do any call-convention-transforming optimizations, and for mundane setup that all the functions need like just initializing static data

**Comment by ludamad** [comment]
@kevaundray thoughts on this?

**Comment by ludamad** [comment]
@kevaundray ping

**Comment by kevaundray** [comment]
If theres no strong conviction to add this then I'd opt to not merge and leave the issue open, so that we can discuss this better when Brillig is in a more stable state. I'd lean towards the status quo since it forces us to be intentional about the way we handle call stacks

**Comment by TomAFrench** [comment]
Based on the above, I'm going to close this PR. We can reopen it after the discussions have been had.

**Pull request closed without merging**
