### PR TITLE
chore: Release 0.18.2

### PR DESCRIPTION
**Pull request by kevaundray**
:robot: I have created a release *beep* *boop*
---

<details><summary>root: 0.18.2</summary>

### Features

* **acvm:** reexport `blackbox_solver` crate from `acvm` ([#431](https://github.com/noir-lang/acvm/issues/431)) ([517e942](https://github.com/noir-lang/acvm/commit/517e942b732d7107f6e064c6791917d1508229b3))
* **stdlib:** Add fallback implementation of `Blake2s` black box function ([#424](https://github.com/noir-lang/acvm/issues/424)) ([982d940](https://github.com/noir-lang/acvm/commit/982d94087d46092ce7a5e94dbd7e732195f58e42))
</details>

<details><summary>acir: 0.18.2</summary>

### Miscellaneous Chores

* **acir:** Synchronize acvm versions
</details>

<details><summary>acir_field: 0.18.2</summary>

### Miscellaneous Chores

* **acir_field:** Synchronize acvm versions
</details>

<details><summary>acvm: 0.18.2</summary>

### Features

* **acvm:** reexport `blackbox_solver` crate from `acvm` ([#431](https://github.com/noir-lang/acvm/issues/431)) ([517e942](https://github.com/noir-lang/acvm/commit/517e942b732d7107f6e064c6791917d1508229b3))
* **stdlib:** Add fallback implementation of `Blake2s` black box function ([#424](https://github.com/noir-lang/acvm/issues/424)) ([982d940](https://github.com/noir-lang/acvm/commit/982d94087d46092ce7a5e94dbd7e732195f58e42))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * brillig_vm bumped from 0.18.1 to 0.18.2
</details>

<details><summary>acvm_blackbox_solver: 0.18.2</summary>

### Miscellaneous Chores

* **acvm_blackbox_solver:** Synchronize acvm versions
</details>

<details><summary>acvm_stdlib: 0.18.2</summary>

### Features

* **stdlib:** Add fallback implementation of `Blake2s` black box function ([#424](https://github.com/noir-lang/acvm/issues/424)) ([982d940](https://github.com/noir-lang/acvm/commit/982d94087d46092ce7a5e94dbd7e732195f58e42))
</details>

<details><summary>brillig: 0.18.2</summary>

### Miscellaneous Chores

* **brillig:** Synchronize acvm versions
</details>

<details><summary>brillig_vm: 0.18.2</summary>

### Miscellaneous Chores

* **brillig_vm:** Synchronize acvm versions
</details>

---
This PR was generated with [Release Please](https://github.com/googleapis/release-please). See [documentation](https://github.com/googleapis/release-please#release-please).

### CODE REVIEW

**Review by TomAFrench — APPROVED** [review]
Pushing this out as it's non-breaking and we can start using it in acvm_js

**Comment by kevaundray** [comment]
:robot: Release is at https://github.com/noir-lang/acvm/releases/tag/root-v0.18.2 :sunflower:

**Comment by kevaundray** [comment]
:robot: Release is at https://github.com/noir-lang/acvm/releases/tag/acir-v0.18.2 :sunflower:

**Comment by kevaundray** [comment]
:robot: Release is at https://github.com/noir-lang/acvm/releases/tag/acir_field-v0.18.2 :sunflower:

**Comment by kevaundray** [comment]
:robot: Release is at https://github.com/noir-lang/acvm/releases/tag/acvm-v0.18.2 :sunflower:

**Comment by kevaundray** [comment]
:robot: Release is at https://github.com/noir-lang/acvm/releases/tag/brillig-v0.18.2 :sunflower:

**Comment by kevaundray** [comment]
:robot: Release is at https://github.com/noir-lang/acvm/releases/tag/brillig_vm-v0.18.2 :sunflower:

**Comment by kevaundray** [comment]
:robot: Release is at https://github.com/noir-lang/acvm/releases/tag/acvm_stdlib-v0.18.2 :sunflower:

**Comment by kevaundray** [comment]
:robot: Release is at https://github.com/noir-lang/acvm/releases/tag/acvm_blackbox_solver-v0.18.2 :sunflower:

**Pull request merged**
