### PR TITLE
chore(acvm)!: remove `prove_with_meta` and `verify_from_cs` from `ProofSystemCompiler`

### LINKED ISSUE #139: Remove `prove_with_meta` and `verify_from_cs`
### Problem

@vezenovm said we don't use `prove_with_meta` and `verify_from_cs` anymore. We should remove them from the `ProofSystemCompiler` trait so we don't need to implement them in backends.

### Proposed solution

Remove them, as they are already marked as deprecated. 

### Alternatives considered

_No response_

### Additional context

Ref https://github.com/noir-lang/aztec_backend/pull/82

### PR DESCRIPTION
**Pull request by TomAFrench**
# Related issue(s)

Resolves #139 

# Description

## Summary of changes

I've removed the deprecated methods from `ProofSystemCompiler` so that they no longer need to be implemented by backends.

## Dependency additions / changes

(If applicable.)

## Test additions / changes

(If applicable.)

# Checklist

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` with default settings.
- [x] I have [linked](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) this PR to the issue(s) that it resolves.
- [x] I have reviewed the changes on GitHub, line by line.
- [x] I have ensured all changes are covered in the description.

# Additional context

(If applicable.)

### CODE REVIEW

**Comment by phated** [comment]
Do we want to hold this PR until 0.7 is closer? I know @guipublic has #138 that wouldn't be breaking and could be released in a 0.6.1

**Comment by TomAFrench** [comment]
True, we could hold this to be merged with #137 if we want to avoid another breaking release.

**Comment by TomAFrench** [comment]
We also have #56 however.

**Comment by TomAFrench** [comment]
@phated #142 got merged so the next release will be breaking.

**Review by phated — APPROVED** [review]

**Pull request merged**
