### PR TITLE
chore(ci): Leverage reusable workflows

### PR DESCRIPTION
**Pull request by phated**
# Related issue(s)

(If it does not already exist, first create a GitHub issue that describes the problem this Pull Request (PR) solves before creating the PR and link it here.)

# Description

This updates ACVM's CI to use our reusable workflows. This will keep CI in sync across all our repositories.

## Summary of changes

(Describe the changes in this PR. Point out breaking changes if any.)

## Dependency additions / changes

(If applicable.)

## Test additions / changes

(If applicable.)

# Checklist

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` with default settings.
- [x] I have [linked](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) this PR to the issue(s) that it resolves.
- [x] I have reviewed the changes on GitHub, line by line.
- [x] I have ensured all changes are covered in the description.

# Additional context

(If applicable.)

### CODE REVIEW

**Comment by kevaundray** [comment]
Interesting that mac-os stable takes a long time on a pure rust project too

**Comment by phated** [comment]
@kevaundray I'm not sure I'm seeing the same thing as you? I'm seeing Mac & Linux run in roughly (~2 minutes) the same amount of time.

There might be a delay in acquiring a Mac runner, but it the build seems consistent when not rebuilding BB.

**Comment by phated** [comment]
Also, how should we handle the clippy failures? In this PR or a separate?

**Comment by jfecher** [comment]
I'm thinking a separate PR for the clippy errors

**Review by jfecher — APPROVED** [review]

**Comment by phated** [comment]
Rebased with that clippy fix

**Pull request merged**
