### PR TITLE
chore: Release 0.20.1

### PR DESCRIPTION
**Pull request by kevaundray**
:robot: I have created a release *beep* *boop*
---

<details><summary>root: 0.20.1</summary>

### Features

* add optimisations to fallback black box functions on booleans ([#446](https://github.com/noir-lang/acvm/issues/446)) ([2cfb2a8](https://github.com/noir-lang/acvm/commit/2cfb2a8cf911a81eedbd9da13ab2c616abd67f83))
* **stdlib:** Add fallback implementation of `Keccak256` black box function ([#445](https://github.com/noir-lang/acvm/issues/445)) ([f7ebb03](https://github.com/noir-lang/acvm/commit/f7ebb03653c971f119700ff8126d9eb5ff01be0f))
</details>

<details><summary>acir: 0.20.1</summary>

### Miscellaneous Chores

* **acir:** Synchronize acvm versions
</details>

<details><summary>acir_field: 0.20.1</summary>

### Miscellaneous Chores

* **acir_field:** Synchronize acvm versions
</details>

<details><summary>acvm: 0.20.1</summary>

### Features

* **stdlib:** Add fallback implementation of `Keccak256` black box function ([#445](https://github.com/noir-lang/acvm/issues/445)) ([f7ebb03](https://github.com/noir-lang/acvm/commit/f7ebb03653c971f119700ff8126d9eb5ff01be0f))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * brillig_vm bumped from 0.20.0 to 0.20.1
</details>

<details><summary>acvm_blackbox_solver: 0.20.1</summary>

### Miscellaneous Chores

* **acvm_blackbox_solver:** Synchronize acvm versions
</details>

<details><summary>acvm_stdlib: 0.20.1</summary>

### Features

* add optimisations to fallback black box functions on booleans ([#446](https://github.com/noir-lang/acvm/issues/446)) ([2cfb2a8](https://github.com/noir-lang/acvm/commit/2cfb2a8cf911a81eedbd9da13ab2c616abd67f83))
* **stdlib:** Add fallback implementation of `Keccak256` black box function ([#445](https://github.com/noir-lang/acvm/issues/445)) ([f7ebb03](https://github.com/noir-lang/acvm/commit/f7ebb03653c971f119700ff8126d9eb5ff01be0f))
</details>

<details><summary>brillig: 0.20.1</summary>

### Miscellaneous Chores

* **brillig:** Synchronize acvm versions
</details>

<details><summary>brillig_vm: 0.20.1</summary>

### Miscellaneous Chores

* **brillig_vm:** Synchronize acvm versions
</details>

---
This PR was generated with [Release Please](https://github.com/googleapis/release-please). See [documentation](https://github.com/googleapis/release-please#release-please).

### CODE REVIEW

**Review by TomAFrench — APPROVED** [review]
Pushing this out as stepwise ACVM will be breaking.

**Comment by kevaundray** [comment]
:robot: Release is at https://github.com/noir-lang/acvm/releases/tag/acir_field-v0.20.1 :sunflower:

**Comment by kevaundray** [comment]
:robot: Release is at https://github.com/noir-lang/acvm/releases/tag/acvm-v0.20.1 :sunflower:

**Comment by kevaundray** [comment]
:robot: Release is at https://github.com/noir-lang/acvm/releases/tag/brillig-v0.20.1 :sunflower:

**Comment by kevaundray** [comment]
:robot: Release is at https://github.com/noir-lang/acvm/releases/tag/brillig_vm-v0.20.1 :sunflower:

**Comment by kevaundray** [comment]
:robot: Release is at https://github.com/noir-lang/acvm/releases/tag/acvm_stdlib-v0.20.1 :sunflower:

**Comment by kevaundray** [comment]
:robot: Release is at https://github.com/noir-lang/acvm/releases/tag/acvm_blackbox_solver-v0.20.1 :sunflower:

**Pull request merged**
