### PR TITLE
chore: Release 0.22.0

### PR DESCRIPTION
**Pull request by kevaundray**
:robot: I have created a release *beep* *boop*
---

<details><summary>root: 0.22.0</summary>

### ⚠ BREAKING CHANGES

* Switched from OpcodeLabel to OpcodeLocation and ErrorLocation ([#493](https://github.com/noir-lang/acvm/issues/493))
* **acvm:** check for index out-of-bounds on memory operations ([#468](https://github.com/noir-lang/acvm/issues/468))

### Features

* **acvm:** check for index out-of-bounds on memory operations ([#468](https://github.com/noir-lang/acvm/issues/468)) ([740468c](https://github.com/noir-lang/acvm/commit/740468c0a144f7179c38f615cfda31b2fcc77359))
* print error location with fmt ([#497](https://github.com/noir-lang/acvm/issues/497)) ([575a9e5](https://github.com/noir-lang/acvm/commit/575a9e50e97afb04a7b91799e06752cec3093f0b))
* Switched from OpcodeLabel to OpcodeLocation and ErrorLocation ([#493](https://github.com/noir-lang/acvm/issues/493)) ([27a5a93](https://github.com/noir-lang/acvm/commit/27a5a935849f8904e10056b08089f532a06962b8))

### Bug Fixes

* add opcode label to unsatisfied constrain string ([#482](https://github.com/noir-lang/acvm/issues/482)) ([cbbbe67](https://github.com/noir-lang/acvm/commit/cbbbe67b9a19a4a560b2dfa8f27ea1c6ebd61f28))
</details>

<details><summary>acir: 0.22.0</summary>

### ⚠ BREAKING CHANGES

* Switched from OpcodeLabel to OpcodeLocation and ErrorLocation ([#493](https://github.com/noir-lang/acvm/issues/493))

### Features

* Switched from OpcodeLabel to OpcodeLocation and ErrorLocation ([#493](https://github.com/noir-lang/acvm/issues/493)) ([27a5a93](https://github.com/noir-lang/acvm/commit/27a5a935849f8904e10056b08089f532a06962b8))
</details>

<details><summary>acir_field: 0.22.0</summary>

### Miscellaneous Chores

* **acir_field:** Synchronize acvm versions
</details>

<details><summary>acvm: 0.22.0</summary>

### ⚠ BREAKING CHANGES

* Switched from OpcodeLabel to OpcodeLocation and ErrorLocation ([#493](https://github.com/noir-lang/acvm/issues/493))
* **acvm:** check for index out-of-bounds on memory operations ([#468](https://github.com/noir-lang/acvm/issues/468))

### Features

* **acvm:** check for index out-of-bounds on memory operations ([#468](https://github.com/noir-lang/acvm/issues/468)) ([740468c](https://github.com/noir-lang/acvm/commit/740468c0a144f7179c38f615cfda31b2fcc77359))
* print error location with fmt ([#497](https://github.com/noir-lang/acvm/issues/497)) ([575a9e5](https://github.com/noir-lang/acvm/commit/575a9e50e97afb04a7b91799e06752cec3093f0b))
* Switched from OpcodeLabel to OpcodeLocation and ErrorLocation ([#493](https://github.com/noir-lang/acvm/issues/493)) ([27a5a93](https://github.com/noir-lang/acvm/commit/27a5a935849f8904e10056b08089f532a06962b8))

### Bug Fixes

* add opcode label to unsatisfied constrain string ([#482](https://github.com/noir-lang/acvm/issues/482)) ([cbbbe67](https://github.com/noir-lang/acvm/commit/cbbbe67b9a19a4a560b2dfa8f27ea1c6ebd61f28))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * brillig_vm bumped from 0.21.0 to 0.22.0
</details>

<details><summary>acvm_blackbox_solver: 0.22.0</summary>

### Miscellaneous Chores

* **acvm_blackbox_solver:** Synchronize acvm versions
</details>

<details><summary>acvm_js: 0.22.0</summary>

### Bug Fixes

* Empty commit to trigger release-please ([e8f0748](https://github.com/noir-lang/acvm/commit/e8f0748042ef505d59ab63266d3c36c5358ee30d))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * acvm bumped from 0.21.0 to 0.22.0
</details>

<details><summary>acvm_stdlib: 0.22.0</summary>

### Miscellaneous Chores

* **acvm_stdlib:** Synchronize acvm versions
</details>

<details><summary>brillig: 0.22.0</summary>

### Miscellaneous Chores

* **brillig:** Synchronize acvm versions
</details>

<details><summary>brillig_vm: 0.22.0</summary>

### Miscellaneous Chores

* **brillig_vm:** Synchronize acvm versions
</details>

---
This PR was generated with [Release Please](https://github.com/googleapis/release-please). See [documentation](https://github.com/googleapis/release-please#release-please).

### CODE REVIEW

**Review by sirasistant — APPROVED** [review]

**Comment by kevaundray** [comment]
:robot: Release is at https://github.com/noir-lang/acvm/releases/tag/root-v0.22.0 :sunflower:

**Comment by kevaundray** [comment]
:robot: Release is at https://github.com/noir-lang/acvm/releases/tag/acir-v0.22.0 :sunflower:

**Comment by kevaundray** [comment]
:robot: Release is at https://github.com/noir-lang/acvm/releases/tag/acir_field-v0.22.0 :sunflower:

**Comment by kevaundray** [comment]
:robot: Release is at https://github.com/noir-lang/acvm/releases/tag/acvm-v0.22.0 :sunflower:

**Comment by kevaundray** [comment]
:robot: Release is at https://github.com/noir-lang/acvm/releases/tag/acvm_js-v0.22.0 :sunflower:

**Comment by kevaundray** [comment]
:robot: Release is at https://github.com/noir-lang/acvm/releases/tag/brillig-v0.22.0 :sunflower:

**Comment by kevaundray** [comment]
:robot: Release is at https://github.com/noir-lang/acvm/releases/tag/brillig_vm-v0.22.0 :sunflower:

**Comment by kevaundray** [comment]
:robot: Release is at https://github.com/noir-lang/acvm/releases/tag/acvm_stdlib-v0.22.0 :sunflower:

**Comment by kevaundray** [comment]
:robot: Release is at https://github.com/noir-lang/acvm/releases/tag/acvm_blackbox_solver-v0.22.0 :sunflower:

**Pull request merged**
