### PR TITLE
chore: Release 0.23.0

### PR DESCRIPTION
**Pull request by kevaundray**
:robot: I have created a release *beep* *boop*
---

<details><summary>root: 0.23.0</summary>

### ⚠ BREAKING CHANGES

* Return an iterator from `new_locations()` instead of collecting ([#507](https://github.com/noir-lang/acvm/issues/507))
* **acvm:** remove `CommonReferenceString` trait and preprocess method ([#508](https://github.com/noir-lang/acvm/issues/508))
* **acvm:** Remove `BlackBoxFunctionSolver` from `Backend` trait ([#494](https://github.com/noir-lang/acvm/issues/494))
* **acvm:** Pass `BlackBoxFunctionSolver` to `ACVM` by reference

### Features

* **acvm_js:** Add `execute_circuit_with_black_box_solver` to prevent reinitialization of `BlackBoxFunctionSolver` ([3877e0e](https://github.com/noir-lang/acvm/commit/3877e0e438a8d0e5545a4da7210767dec05c342f))
* Expose a `BlackBoxFunctionSolver` containing a barretenberg wasm from `blackbox_solver` ([#494](https://github.com/noir-lang/acvm/issues/494)) ([a1d4b71](https://github.com/noir-lang/acvm/commit/a1d4b71256dfbf1e883e770dd9c45479235aa860))

### Miscellaneous Chores

* **acvm:** Pass `BlackBoxFunctionSolver` to `ACVM` by reference ([3877e0e](https://github.com/noir-lang/acvm/commit/3877e0e438a8d0e5545a4da7210767dec05c342f))
* **acvm:** Remove `BlackBoxFunctionSolver` from `Backend` trait ([#494](https://github.com/noir-lang/acvm/issues/494)) ([a1d4b71](https://github.com/noir-lang/acvm/commit/a1d4b71256dfbf1e883e770dd9c45479235aa860))
* **acvm:** remove `CommonReferenceString` trait and preprocess method ([#508](https://github.com/noir-lang/acvm/issues/508)) ([3827dd3](https://github.com/noir-lang/acvm/commit/3827dd3ce487650843ba4df8337b423e39f97edf))
* Return an iterator from `new_locations()` instead of collecting ([#507](https://github.com/noir-lang/acvm/issues/507)) ([8d49a5c](https://github.com/noir-lang/acvm/commit/8d49a5c15b1e962cd59252467a20a922edadc2f2))
</details>

<details><summary>acir: 0.23.0</summary>

### Miscellaneous Chores

* **acir:** Synchronize acvm versions
</details>

<details><summary>acir_field: 0.23.0</summary>

### Miscellaneous Chores

* **acir_field:** Synchronize acvm versions
</details>

<details><summary>acvm: 0.23.0</summary>

### ⚠ BREAKING CHANGES

* Return an iterator from `new_locations()` instead of collecting ([#507](https://github.com/noir-lang/acvm/issues/507))
* **acvm:** remove `CommonReferenceString` trait and preprocess method ([#508](https://github.com/noir-lang/acvm/issues/508))
* **acvm:** Pass `BlackBoxFunctionSolver` to `ACVM` by reference

### Features

* **acvm_js:** Add `execute_circuit_with_black_box_solver` to prevent reinitialization of `BlackBoxFunctionSolver` ([3877e0e](https://github.com/noir-lang/acvm/commit/3877e0e438a8d0e5545a4da7210767dec05c342f))

### Miscellaneous Chores

* **acvm:** Pass `BlackBoxFunctionSolver` to `ACVM` by reference ([3877e0e](https://github.com/noir-lang/acvm/commit/3877e0e438a8d0e5545a4da7210767dec05c342f))
* **acvm:** remove `CommonReferenceString` trait and preprocess method ([#508](https://github.com/noir-lang/acvm/issues/508)) ([3827dd3](https://github.com/noir-lang/acvm/commit/3827dd3ce487650843ba4df8337b423e39f97edf))
* Return an iterator from `new_locations()` instead of collecting ([#507](https://github.com/noir-lang/acvm/issues/507)) ([8d49a5c](https://github.com/noir-lang/acvm/commit/8d49a5c15b1e962cd59252467a20a922edadc2f2))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * brillig_vm bumped from 0.22.0 to 0.23.0
</details>

<details><summary>acvm_blackbox_solver: 0.23.0</summary>

### ⚠ BREAKING CHANGES

* **acvm:** Remove `BlackBoxFunctionSolver` from `Backend` trait ([#494](https://github.com/noir-lang/acvm/issues/494))

### Features

* Expose a `BlackBoxFunctionSolver` containing a barretenberg wasm from `blackbox_solver` ([#494](https://github.com/noir-lang/acvm/issues/494)) ([a1d4b71](https://github.com/noir-lang/acvm/commit/a1d4b71256dfbf1e883e770dd9c45479235aa860))

### Miscellaneous Chores

* **acvm:** Remove `BlackBoxFunctionSolver` from `Backend` trait ([#494](https://github.com/noir-lang/acvm/issues/494)) ([a1d4b71](https://github.com/noir-lang/acvm/commit/a1d4b71256dfbf1e883e770dd9c45479235aa860))
</details>

<details><summary>acvm_js: 0.23.0</summary>

### ⚠ BREAKING CHANGES

* **acvm:** Remove `BlackBoxFunctionSolver` from `Backend` trait ([#494](https://github.com/noir-lang/acvm/issues/494))
* **acvm:** Pass `BlackBoxFunctionSolver` to `ACVM` by reference

### Features

* **acvm_js:** Add `execute_circuit_with_black_box_solver` to prevent reinitialization of `BlackBoxFunctionSolver` ([3877e0e](https://github.com/noir-lang/acvm/commit/3877e0e438a8d0e5545a4da7210767dec05c342f))
* Expose a `BlackBoxFunctionSolver` containing a barretenberg wasm from `blackbox_solver` ([#494](https://github.com/noir-lang/acvm/issues/494)) ([a1d4b71](https://github.com/noir-lang/acvm/commit/a1d4b71256dfbf1e883e770dd9c45479235aa860))

### Miscellaneous Chores

* **acvm:** Pass `BlackBoxFunctionSolver` to `ACVM` by reference ([3877e0e](https://github.com/noir-lang/acvm/commit/3877e0e438a8d0e5545a4da7210767dec05c342f))
* **acvm:** Remove `BlackBoxFunctionSolver` from `Backend` trait ([#494](https://github.com/noir-lang/acvm/issues/494)) ([a1d4b71](https://github.com/noir-lang/acvm/commit/a1d4b71256dfbf1e883e770dd9c45479235aa860))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * acvm bumped from 0.22.0 to 0.23.0
</details>

<details><summary>acvm_stdlib: 0.23.0</summary>

### Miscellaneous Chores

* **acvm_stdlib:** Synchronize acvm versions
</details>

<details><summary>brillig: 0.23.0</summary>

### Miscellaneous Chores

* **brillig:** Synchronize acvm versions
</details>

<details><summary>brillig_vm: 0.23.0</summary>

### Miscellaneous Chores

* **brillig_vm:** Synchronize acvm versions
</details>

---
This PR was generated with [Release Please](https://github.com/googleapis/release-please). See [documentation](https://github.com/googleapis/release-please#release-please).

### CODE REVIEW

**Review by TomAFrench — APPROVED** [review]

**Comment by kevaundray** [comment]
:robot: Release is at https://github.com/noir-lang/acvm/releases/tag/root-v0.23.0 :sunflower:

**Comment by kevaundray** [comment]
:robot: Release is at https://github.com/noir-lang/acvm/releases/tag/acir-v0.23.0 :sunflower:

**Comment by kevaundray** [comment]
:robot: Release is at https://github.com/noir-lang/acvm/releases/tag/acvm_js-v0.23.0 :sunflower:

**Comment by kevaundray** [comment]
:robot: Release is at https://github.com/noir-lang/acvm/releases/tag/brillig-v0.23.0 :sunflower:

**Comment by kevaundray** [comment]
:robot: Release is at https://github.com/noir-lang/acvm/releases/tag/brillig_vm-v0.23.0 :sunflower:

**Comment by kevaundray** [comment]
:robot: Release is at https://github.com/noir-lang/acvm/releases/tag/acvm_stdlib-v0.23.0 :sunflower:

**Comment by kevaundray** [comment]
:robot: Release is at https://github.com/noir-lang/acvm/releases/tag/acvm_blackbox_solver-v0.23.0 :sunflower:

**Pull request merged**
