### PR TITLE
chore!: backend can specify which opcode they support

### PR DESCRIPTION
**Pull request by guipublic**
# Description

## Summary of changes

replace blackbox_supported with opcode_supported

## Dependency additions / changes

(If applicable.)

## Test additions / changes

(If applicable.)

# Checklist

- [ ] I have tested the changes locally.
- [X] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` with default settings.
- [ ] I have [linked](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) this PR to the issue(s) that it resolves.
- [X] I have reviewed the changes on GitHub, line by line.
- [X] I have ensured all changes are covered in the description.

# Additional context

This is useful for memory opcodes, we could have a TP backend which supports only ROM opcode for instance.

### CODE REVIEW

**Comment by TomAFrench** [comment]
Can you address the other point in https://github.com/noir-lang/acvm/issues/183 in this PR?

**Comment by guipublic** [comment]
> Can you address the other point in #183 in this PR?

I was addressing them directly in #183

**Comment by TomAFrench** [comment]
Sorry I don't follow, can you clarify what you mean? This PR as it is won't allow us to pass `backend.opcode_supported` into `acvm::compile`

**Comment by guipublic** [comment]
> Sorry I don't follow, can you clarify what you mean? This PR as it is won't allow us to pass `backend.opcode_supported` into `acvm::compile`

My bad, I thought you were talking about PR 153 on aztec backend (not the same repo and even not the same number...), sorry for the confusion.
I will look at the issue 183.

**Comment by TomAFrench** [comment]
Closing in favour of #273

**Pull request closed without merging**
