### PR TITLE
chore: Release 0.26.0

### PR DESCRIPTION
**Pull request by kevaundray**
:robot: I have created a release *beep* *boop*
---

<details><summary>root: 0.26.0</summary>

### ⚠ BREAKING CHANGES

* Add a low and high limb to scalar mul opcode ([#532](https://github.com/noir-lang/acvm/issues/532))

### Miscellaneous Chores

* Add a low and high limb to scalar mul opcode ([#532](https://github.com/noir-lang/acvm/issues/532)) ([b054f66](https://github.com/noir-lang/acvm/commit/b054f66be9c73d4e02dbecdab80874a907f19242))
</details>

<details><summary>acir: 0.26.0</summary>

### ⚠ BREAKING CHANGES

* Add a low and high limb to scalar mul opcode ([#532](https://github.com/noir-lang/acvm/issues/532))

### Miscellaneous Chores

* Add a low and high limb to scalar mul opcode ([#532](https://github.com/noir-lang/acvm/issues/532)) ([b054f66](https://github.com/noir-lang/acvm/commit/b054f66be9c73d4e02dbecdab80874a907f19242))
</details>

<details><summary>acir_field: 0.26.0</summary>

### Miscellaneous Chores

* **acir_field:** Synchronize acvm versions
</details>

<details><summary>acvm: 0.26.0</summary>

### ⚠ BREAKING CHANGES

* Add a low and high limb to scalar mul opcode ([#532](https://github.com/noir-lang/acvm/issues/532))

### Miscellaneous Chores

* Add a low and high limb to scalar mul opcode ([#532](https://github.com/noir-lang/acvm/issues/532)) ([b054f66](https://github.com/noir-lang/acvm/commit/b054f66be9c73d4e02dbecdab80874a907f19242))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * brillig_vm bumped from 0.25.0 to 0.26.0
</details>

<details><summary>acvm_blackbox_solver: 0.26.0</summary>

### ⚠ BREAKING CHANGES

* Add a low and high limb to scalar mul opcode ([#532](https://github.com/noir-lang/acvm/issues/532))

### Miscellaneous Chores

* Add a low and high limb to scalar mul opcode ([#532](https://github.com/noir-lang/acvm/issues/532)) ([b054f66](https://github.com/noir-lang/acvm/commit/b054f66be9c73d4e02dbecdab80874a907f19242))
</details>

<details><summary>acvm_js: 0.26.0</summary>

### ⚠ BREAKING CHANGES

* Add a low and high limb to scalar mul opcode ([#532](https://github.com/noir-lang/acvm/issues/532))

### Miscellaneous Chores

* Add a low and high limb to scalar mul opcode ([#532](https://github.com/noir-lang/acvm/issues/532)) ([b054f66](https://github.com/noir-lang/acvm/commit/b054f66be9c73d4e02dbecdab80874a907f19242))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * acvm bumped from 0.25.0 to 0.26.0
</details>

<details><summary>acvm_stdlib: 0.26.0</summary>

### Miscellaneous Chores

* **acvm_stdlib:** Synchronize acvm versions
</details>

<details><summary>brillig: 0.26.0</summary>

### ⚠ BREAKING CHANGES

* Add a low and high limb to scalar mul opcode ([#532](https://github.com/noir-lang/acvm/issues/532))

### Miscellaneous Chores

* Add a low and high limb to scalar mul opcode ([#532](https://github.com/noir-lang/acvm/issues/532)) ([b054f66](https://github.com/noir-lang/acvm/commit/b054f66be9c73d4e02dbecdab80874a907f19242))
</details>

<details><summary>brillig_vm: 0.26.0</summary>

### ⚠ BREAKING CHANGES

* Add a low and high limb to scalar mul opcode ([#532](https://github.com/noir-lang/acvm/issues/532))

### Miscellaneous Chores

* Add a low and high limb to scalar mul opcode ([#532](https://github.com/noir-lang/acvm/issues/532)) ([b054f66](https://github.com/noir-lang/acvm/commit/b054f66be9c73d4e02dbecdab80874a907f19242))
</details>

---
This PR was generated with [Release Please](https://github.com/googleapis/release-please). See [documentation](https://github.com/googleapis/release-please#release-please).

### CODE REVIEW

**Review by vezenovm — APPROVED** [review]

**Comment by kevaundray** [comment]
:robot: Release is at https://github.com/noir-lang/acvm/releases/tag/root-v0.26.0 :sunflower:

**Comment by kevaundray** [comment]
:robot: Release is at https://github.com/noir-lang/acvm/releases/tag/acir-v0.26.0 :sunflower:

**Comment by kevaundray** [comment]
:robot: Release is at https://github.com/noir-lang/acvm/releases/tag/acir_field-v0.26.0 :sunflower:

**Comment by kevaundray** [comment]
:robot: Release is at https://github.com/noir-lang/acvm/releases/tag/acvm-v0.26.0 :sunflower:

**Comment by kevaundray** [comment]
:robot: Release is at https://github.com/noir-lang/acvm/releases/tag/acvm_js-v0.26.0 :sunflower:

**Comment by kevaundray** [comment]
:robot: Release is at https://github.com/noir-lang/acvm/releases/tag/brillig-v0.26.0 :sunflower:

**Comment by kevaundray** [comment]
:robot: Release is at https://github.com/noir-lang/acvm/releases/tag/brillig_vm-v0.26.0 :sunflower:

**Comment by kevaundray** [comment]
:robot: Release is at https://github.com/noir-lang/acvm/releases/tag/acvm_stdlib-v0.26.0 :sunflower:

**Comment by kevaundray** [comment]
:robot: Release is at https://github.com/noir-lang/acvm/releases/tag/acvm_blackbox_solver-v0.26.0 :sunflower:

**Pull request merged**
